### ISSUE TITLE
小

### ISSUE THREAD

**Issue by ghost** [sakarika/kanjitomo-ocr#12]
I've noticed that the OCR often has difficulty recognizing 小. It's typically like this with it only recognizing the strokes on the edges.

![小](https://user-images.githubusercontent.com/113230180/211169246-dfb39d0a-a25c-42ab-bd08-afabae2e1d66.png)

I gotta say, even though it hasn't been updated in a while and may never be, kanjitomo is still better than a lot of other options I've seen online even recently. Thanks for making this.

**Comment by sakarika** [comment]
Thank you for the report. KanjiTomo is not under active development so this is unlikely to be fixed.

The problem is that the algorithm is pretty outdated at this point. OCR would be better solved by neural networks these days. Current algorithm is fragile and requires lots of hand-tuning; it's very difficult to improve detection of one character without making other cases worse.

**Comment by ghost** [comment]
Thank you for the response!

2023年1月8日(日) 9:37 sakarika ***@***.***>:
